# Generated by Django 5.2.12 on 2026-03-23 16:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_start_time",
                    models.TimeField(
                        default=datetime.time(9, 0), verbose_name="Çalışma Başlangıç"
                    ),
                ),
                (
                    "work_end_time",
                    models.TimeField(
                        default=datetime.time(18, 0), verbose_name="Çalışma Bitiş"
                    ),
                ),
                (
                    "appointment_interval_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Randevu Aralığı (dk)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Klinik Ayarı",
                "verbose_name_plural": "Klinik Ayarları",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "tckn",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="TC Kimlik No"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hasta",
                "verbose_name_plural": "Hastalar",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tedavi Türü")),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Varsayılan Fiyat",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Tedavi Türü",
                "verbose_name_plural": "Tedavi Türleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                ("time", models.TimeField(verbose_name="Saat")),
                (
                    "duration",
                    models.PositiveIntegerField(default=60, verbose_name="Süre (dk)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planlandı"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal"),
                            ("no_show", "Gelmedi"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "treatment_type",
                    models.CharField(blank=True, max_length=200, verbose_name="İşlem"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Randevu",
                "verbose_name_plural": "Randevular",
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="Anamnesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, verbose_name="Tıbbi Geçmiş"),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Alerjiler")),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="Kullandığı İlaçlar"),
                ),
                (
                    "chronic_diseases",
                    models.TextField(blank=True, verbose_name="Kronik Hastalıklar"),
                ),
                (
                    "surgical_history",
                    models.TextField(blank=True, verbose_name="Geçirdiği Ameliyatlar"),
                ),
                (
                    "family_history",
                    models.TextField(blank=True, verbose_name="Aile Öyküsü"),
                ),
                (
                    "smoking",
                    models.CharField(blank=True, max_length=100, verbose_name="Sigara"),
                ),
                (
                    "alcohol",
                    models.CharField(blank=True, max_length=100, verbose_name="Alkol"),
                ),
                (
                    "pregnancy_status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Gebelik Durumu"
                    ),
                ),
                (
                    "other_notes",
                    models.TextField(blank=True, verbose_name="Diğer Notlar"),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anamnesis",
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anamnez",
                "verbose_name_plural": "Anamnezler",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tutar"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Açıklama"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Ödeme Tarihi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme",
                "verbose_name_plural": "Ödemeler",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="İşlem Adı"
                    ),
                ),
                (
                    "tooth_number",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Diş No (FDI)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Yapılacak"),
                            ("completed", "Tamamlanmış"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                ("date", models.DateField(verbose_name="Tarih")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="api.patient",
                    ),
                ),
                (
                    "treatment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments",
                        to="api.treatmenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tedavi",
                "verbose_name_plural": "Tedaviler",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
