# Generated by Django 5.2.12 on 2026-05-21 15:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "İşlem Logu",
                "verbose_name_plural": "İşlem Logları",
            },
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="object_repr",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 5, 21, 15, 30, 12, 139395, tzinfo=datetime.timezone.utc
                ),
                verbose_name="İşlem Tarihi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP Adresi"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Oluşturma"),
                    ("UPDATE", "Güncelleme"),
                    ("DELETE", "Silme"),
                ],
                max_length=10,
                verbose_name="İşlem Tipi",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(blank=True, null=True, verbose_name="Değişiklikler"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
    ]
