# Generated by Django 5.2.12 on 2026-03-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clinicsettings_patient_treatmenttype_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='work_days',
            field=models.JSONField(blank=True, default=list, help_text='Örn: 0,1,2,3,4,5 (0=Pzt, 6=Paz)', verbose_name='Çalışılabilecek Günler'),
        ),
    ]
