# Generated by Django 6.0.4 on 2026-05-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_auditlog_options_remove_auditlog_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='treatment_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.treatment', verbose_name='Bağlı Tedavi'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tckn',
            field=models.CharField(max_length=11, verbose_name='TC Kimlik No'),
        ),
    ]
