# Generated by Django 6.0.5 on 2026-05-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appointment_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='tckn',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik No'),
        ),
    ]
