# Generated by Django 5.2.12 on 2026-03-28 11:53

from django.db import migrations

def create_default_clinic_and_assign_data(apps, schema_editor):
    Clinic = apps.get_model('api', 'Clinic')
    CustomUser = apps.get_model('api', 'CustomUser')
    Patient = apps.get_model('api', 'Patient')
    TreatmentType = apps.get_model('api', 'TreatmentType')
    Appointment = apps.get_model('api', 'Appointment')
    Treatment = apps.get_model('api', 'Treatment')
    ClinicSettings = apps.get_model('api', 'ClinicSettings')
    Payment = apps.get_model('api', 'Payment')

    # Ensure there is a default clinic available if existing data lacks one
    has_null_users = CustomUser.objects.filter(clinic__isnull=True).exists()
    has_null_patients = Patient.objects.filter(clinic__isnull=True).exists()
    
    if has_null_users or has_null_patients:
        default_clinic, _ = Clinic.objects.get_or_create(name="Merkez Klinik")

        CustomUser.objects.filter(clinic__isnull=True).update(clinic=default_clinic)
        Patient.objects.filter(clinic__isnull=True).update(clinic=default_clinic)
        TreatmentType.objects.filter(clinic__isnull=True).update(clinic=default_clinic)
        Appointment.objects.filter(clinic__isnull=True).update(clinic=default_clinic)
        Treatment.objects.filter(clinic__isnull=True).update(clinic=default_clinic)
        ClinicSettings.objects.filter(clinic__isnull=True).update(clinic=default_clinic)
        Payment.objects.filter(clinic__isnull=True).update(clinic=default_clinic)

def reverse_default_clinic_assignment(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clinic_appointment_clinic_clinicsettings_clinic_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_clinic_and_assign_data, reverse_default_clinic_assignment),
    ]
