# Generated by Django 5.2.12 on 2026-03-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20260328_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicsettings',
            name='appointment_interval_minutes',
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='work_days',
            field=models.JSONField(blank=True, default=list, help_text='Örn: 1,2,3,4,5,6 (1=Pzt, 0=Paz)', verbose_name='Çalışılabilecek Günler'),
        ),
    ]
