# Generated by Django 6.0.5 on 2026-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_patient_tckn'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='allow_international_numbers',
            field=models.BooleanField(default=False, verbose_name='Uluslararası Numaralara İzin Ver'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='default_country',
            field=models.CharField(choices=[('TR', 'Türkiye')], default='TR', max_length=2, verbose_name='Varsayılan Ülke'),
        ),
    ]
