# Generated by Django 6.0.4 on 2026-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_clinicsettings_allow_international_numbers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time', 'id'], 'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AddField(
            model_name='treatment',
            name='teeth',
            field=models.JSONField(blank=True, default=list, verbose_name='Dişler/Bölgeler'),
        ),
    ]
