# Generated by Django 6.0.4 on 2026-06-23 12:35

from django.db import migrations


def move_tooth_data(apps, schema_editor):
    Treatment = apps.get_model('api', 'Treatment')
    for treatment in Treatment.objects.all():
        if treatment.tooth_number:
            treatment.teeth = [treatment.tooth_number]
        else:
            treatment.teeth = []
        treatment.save()

def reverse_move_tooth_data(apps, schema_editor):
    Treatment = apps.get_model('api', 'Treatment')
    for treatment in Treatment.objects.all():
        if treatment.teeth and len(treatment.teeth) > 0:
            treatment.tooth_number = str(treatment.teeth[0])
        else:
            treatment.tooth_number = ""
        treatment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_appointment_options_treatment_teeth'),
    ]

    operations = [
        migrations.RunPython(move_tooth_data, reverse_move_tooth_data),
    ]
