# Generated by Django 6.0.4 on 2026-06-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_move_tooth_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='tooth_number',
        ),
    ]
