# Generated by Django 6.0.4 on 2026-05-15 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_document_is_active_payment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.treatmenttype', verbose_name='İşlem Türü'),
        ),
    ]
