# Generated by Django 6.0.4 on 2026-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appointment_is_active_patient_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmenttype',
            name='category',
            field=models.CharField(choices=[('filling', 'Dolgu'), ('canal', 'Kanal Tedavisi'), ('crown', 'Kron / Kaplama'), ('extraction', 'Diş Çekimi'), ('implant', 'İmplant'), ('detartraj', 'Diş Taşı Temizliği'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Kategori'),
        ),
    ]
