# Generated by Django 6.0.5 on 2026-05-20 10:18

from django.db import migrations


def forward(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE api_patient ALTER COLUMN first_name TYPE VARCHAR(100) COLLATE "tr-TR-x-icu";')
        schema_editor.execute('ALTER TABLE api_patient ALTER COLUMN last_name TYPE VARCHAR(100) COLLATE "tr-TR-x-icu";')
        schema_editor.execute('ALTER TABLE api_patient ALTER COLUMN phone TYPE VARCHAR(20) COLLATE "tr-TR-x-icu";')
        schema_editor.execute('ALTER TABLE api_patient ALTER COLUMN tckn TYPE VARCHAR(11) COLLATE "tr-TR-x-icu";')

def backward(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('ALTER TABLE api_patient ALTER COLUMN first_name TYPE VARCHAR(100);')
        schema_editor.execute('ALTER TABLE api_patient ALTER COLUMN last_name TYPE VARCHAR(100);')
        schema_editor.execute('ALTER TABLE api_patient ALTER COLUMN phone TYPE VARCHAR(20);')
        schema_editor.execute('ALTER TABLE api_patient ALTER COLUMN tckn TYPE VARCHAR(11);')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_treatmenttype_category'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
