# Generated by Django 6.0.5 on 2026-05-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_patient_turkish_collation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmenttype',
            name='clinic',
        ),
        migrations.AddField(
            model_name='treatmenttype',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_types', to=settings.AUTH_USER_MODEL, verbose_name='Hekim'),
        ),
    ]
