#!/usr/bin/env python3
"""
Test metrik üreten script.

Backend + frontend test sayılarını parse eder, test pyramid oranını hesaplar,
docs/TEST_METRICS.md dosyasını günceller.

Kullanım:
    python scripts/test-metrics.py [--write]

--write olmadan: stdout'a rapor.
--write ile: docs/TEST_METRICS.md güncellenir.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
FRONTEND = ROOT / "frontend"


def count_backend_tests() -> int:
    """pytest --collect-only ile backend test sayısı."""
    try:
        out = subprocess.run(
            ["python", "-m", "pytest", "--collect-only", "-q"],
            cwd=BACKEND,
            capture_output=True,
            text=True,
            timeout=60,
        )
        # Çıktının son satırı: "X tests collected"
        match = re.search(r"(\d+)\s+tests?\s+collected", out.stdout)
        if match:
            return int(match.group(1))
    except Exception as e:
        print(f"⚠️  Backend test count alınamadı: {e}", file=sys.stderr)
    return 0


def count_frontend_unit_tests() -> int:
    """Vitest test dosyalarındaki it/test bloklarını say."""
    count = 0
    for path in (FRONTEND / "src").rglob("*.test.tsx"):
        try:
            text = path.read_text(encoding="utf-8")
            count += len(re.findall(r"^\s*(?:it|test)\s*\(", text, re.MULTILINE))
        except Exception:
            continue
    for path in (FRONTEND / "src").rglob("*.test.ts"):
        try:
            text = path.read_text(encoding="utf-8")
            count += len(re.findall(r"^\s*(?:it|test)\s*\(", text, re.MULTILINE))
        except Exception:
            continue
    return count


def count_e2e_tests() -> int:
    """Playwright spec dosyalarındaki test() bloklarını say."""
    count = 0
    e2e = FRONTEND / "e2e"
    if not e2e.exists():
        return 0
    for path in e2e.glob("*.spec.ts"):
        try:
            text = path.read_text(encoding="utf-8")
            count += len(re.findall(r"^\s*test\s*\(", text, re.MULTILINE))
        except Exception:
            continue
    return count


def pyramid_percentage(unit: int, integ: int, e2e: int) -> tuple[float, float, float]:
    total = unit + integ + e2e
    if total == 0:
        return (0, 0, 0)
    return (
        round(unit * 100 / total, 1),
        round(integ * 100 / total, 1),
        round(e2e * 100 / total, 1),
    )


def render_report(backend: int, frontend: int, e2e: int) -> str:
    total = backend + frontend + e2e
    # Approximate: backend tests are integration-heavy, frontend unit-heavy
    # Bu basit yaklaşım için: backend = integration, frontend = unit
    pct_unit, pct_integ, pct_e2e = pyramid_percentage(frontend, backend, e2e)

    pyramid_emoji_unit = "✅" if pct_unit >= 60 else "⚠️"
    pyramid_emoji_integ = "✅" if 15 <= pct_integ <= 30 else "⚠️"
    pyramid_emoji_e2e = "✅" if pct_e2e <= 15 else "⚠️"

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    return f"""<!-- AUTO-GENERATED by scripts/test-metrics.py — DO NOT EDIT BY HAND -->

# Test Metrics — Yaşca Dental Clinic

**Son güncelleme:** {now}

## Test Sayıları

| Katman | Test Sayısı | Hedef % | Mevcut % | Durum |
|--------|-------------|---------|----------|-------|
| Frontend unit (vitest) | {frontend} | 70% | {pct_unit}% | {pyramid_emoji_unit} |
| Backend (pytest, integration-heavy) | {backend} | 20% | {pct_integ}% | {pyramid_emoji_integ} |
| E2E (Playwright) | {e2e} | 10% | {pct_e2e}% | {pyramid_emoji_e2e} |
| **Toplam** | **{total}** | | | |

## Test Pyramid Görselleştirme

```
            /\\
           /E2E\\         {pct_e2e}%
          /------\\
         /Backend  \\      {pct_integ}%
        /----------\\
       /  Frontend   \\    {pct_unit}%
      /______________\\
```

## Yorum

{_pyramid_comment(pct_unit, pct_integ, pct_e2e)}

## İlgili Belgeler

- [TEST_PYRAMID.md](TEST_PYRAMID.md) — pyramid hedefi gerekçesi
- [TESTING.md](TESTING.md) — test yazma rehberi
"""


def _pyramid_comment(unit_pct: float, integ_pct: float, e2e_pct: float) -> str:
    parts = []
    if unit_pct < 60:
        parts.append(f"⚠️ Unit testleri ({unit_pct}%) hedefin (70%) altında — daha fazla unit test yazılmalı.")
    if e2e_pct > 15:
        parts.append(f"⚠️ E2E testleri ({e2e_pct}%) hedefin üstünde — bazı E2E'leri unit'e taşımak değerlendirilmeli.")
    if not parts:
        parts.append("✅ Test piramidi sağlıklı.")
    return "\n".join(parts)


def main() -> int:
    # Windows console UTF-8 support
    if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass

    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="docs/TEST_METRICS.md dosyasını güncelle")
    args = parser.parse_args()

    print("[*] Test sayilari toplaniyor...")
    backend = count_backend_tests()
    frontend = count_frontend_unit_tests()
    e2e = count_e2e_tests()

    print(f"  Backend (pytest):     {backend}")
    print(f"  Frontend (vitest):    {frontend}")
    print(f"  E2E (Playwright):     {e2e}")

    report = render_report(backend, frontend, e2e)

    if args.write:
        target = ROOT / "docs" / "TEST_METRICS.md"
        target.write_text(report, encoding="utf-8")
        print(f"\n[OK] {target} guncellendi.")
    else:
        print("\n" + report)

    return 0


if __name__ == "__main__":
    sys.exit(main())
